"""add_a2a_agent_plugin_binding_table

Revision ID: b29af8761e97
Revises: 351b43e1d273
Create Date: 2026-05-15 11:59:42.434761

"""

# Standard
from typing import Sequence, Union

# Third-Party
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "b29af8761e97"
down_revision: Union[str, Sequence[str], None] = "351b43e1d273"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "global_config", sa.Column("id", sa.Integer(), nullable=False), sa.Column("passthrough_headers", sa.JSON(), nullable=True), sa.PrimaryKeyConstraint("id", name=op.f("pk_global_config"))
    )
    op.create_table(
        "mcp_sessions",
        sa.Column("session_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_accessed", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_mcp_sessions")),
    )
    op.create_table(
        "mcp_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_accessed", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["mcp_sessions.session_id"], name=op.f("fk_mcp_messages_session_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mcp_messages")),
    )
    op.create_table(
        "a2a_agent_plugin_bindings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("team_id", sa.String(length=36), nullable=False),
        sa.Column("agent_name", sa.String(length=255), nullable=False),
        sa.Column("plugin_id", sa.String(length=64), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("binding_reference_id", sa.String(length=255), nullable=True),
        sa.Column("on_error", sa.String(length=10), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by", sa.String(length=255), nullable=False),
        sa.CheckConstraint("on_error IN ('fail', 'ignore', 'disable') OR on_error IS NULL", name=op.f("ck_a2a_agent_plugin_bindings_ck_a2a_agent_plugin_bindings_on_error_valid")),
        sa.ForeignKeyConstraint(["team_id"], ["email_teams.id"], name=op.f("fk_a2a_agent_plugin_bindings_team_id"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_a2a_agent_plugin_bindings")),
        sa.UniqueConstraint("team_id", "agent_name", "plugin_id", name="uq_a2a_agent_plugin_binding"),
    )
    op.create_index("ix_a2a_agent_plugin_bindings_agent_name", "a2a_agent_plugin_bindings", ["agent_name"], unique=False)
    op.create_index("ix_a2a_agent_plugin_bindings_binding_reference_id", "a2a_agent_plugin_bindings", ["binding_reference_id"], unique=False)
    op.create_index("ix_a2a_agent_plugin_bindings_team_id", "a2a_agent_plugin_bindings", ["team_id"], unique=False)
    op.create_table(
        "gateways",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=767), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("transport", sa.String(length=20), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("reachable", sa.Boolean(), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("created_from_ip", sa.String(length=45), nullable=True),
        sa.Column("created_via", sa.String(length=100), nullable=True),
        sa.Column("created_user_agent", sa.Text(), nullable=True),
        sa.Column("modified_by", sa.String(length=255), nullable=True),
        sa.Column("modified_from_ip", sa.String(length=45), nullable=True),
        sa.Column("modified_via", sa.String(length=100), nullable=True),
        sa.Column("modified_user_agent", sa.Text(), nullable=True),
        sa.Column("import_batch_id", sa.String(length=36), nullable=True),
        sa.Column("federation_source", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("passthrough_headers", sa.JSON(), nullable=True),
        sa.Column("ca_certificate", sa.Text(), nullable=True),
        sa.Column("ca_certificate_sig", sa.String(length=64), nullable=True),
        sa.Column("signing_algorithm", sa.String(length=20), nullable=True),
        sa.Column("client_cert", sa.Text(), nullable=True),
        sa.Column("client_key", sa.Text(), nullable=True),
        sa.Column("auth_type", sa.String(length=20), nullable=True),
        sa.Column("auth_value", sa.JSON(), nullable=True),
        sa.Column("auth_query_params", sa.JSON(), nullable=True, comment="Encrypted query parameters for auth. Format: {'param_name': 'encrypted_value'}"),
        sa.Column("oauth_config", sa.JSON(), nullable=True, comment="OAuth 2.0 configuration including grant_type, client_id, encrypted client_secret, URLs, and scopes"),
        sa.Column("team_id", sa.String(length=36), nullable=True),
        sa.Column("owner_email", sa.String(length=255), nullable=True),
        sa.Column("visibility", sa.String(length=20), nullable=False),
        sa.Column("refresh_interval_seconds", sa.Integer(), nullable=True, comment="Per-gateway refresh interval in seconds; NULL uses global default"),
        sa.Column("last_refresh_at", sa.DateTime(timezone=True), nullable=True, comment="Timestamp of the last successful tools/resources/prompts refresh"),
        sa.Column("gateway_mode", sa.String(length=20), nullable=False, comment="Gateway mode: 'cache' (database caching) or 'direct_proxy' (pass-through mode)"),
        sa.Column("identity_propagation", sa.JSON(), nullable=True, comment="Per-gateway identity propagation config overrides"),
        sa.ForeignKeyConstraint(["team_id"], ["email_teams.id"], name=op.f("fk_gateways_team_id"), ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gateways")),
        sa.UniqueConstraint("team_id", "owner_email", "slug", name="uq_team_owner_slug_gateway"),
    )
    op.create_index("idx_gateways_created_at_id", "gateways", ["created_at", "id"], unique=False)
    op.create_table(
        "servers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=767), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("created_from_ip", sa.String(length=45), nullable=True),
        sa.Column("created_via", sa.String(length=100), nullable=True),
        sa.Column("created_user_agent", sa.Text(), nullable=True),
        sa.Column("modified_by", sa.String(length=255), nullable=True),
        sa.Column("modified_from_ip", sa.String(length=45), nullable=True),
        sa.Column("modified_via", sa.String(length=100), nullable=True),
        sa.Column("modified_user_agent", sa.Text(), nullable=True),
        sa.Column("import_batch_id", sa.String(length=36), nullable=True),
        sa.Column("federation_source", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.String(length=36), nullable=True),
        sa.Column("owner_email", sa.String(length=255), nullable=True),
        sa.Column("visibility", sa.String(length=20), nullable=False),
        sa.Column("oauth_enabled", sa.Boolean(), nullable=False),
        sa.Column("oauth_config", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["email_teams.id"], name=op.f("fk_servers_team_id"), ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_servers")),
        sa.UniqueConstraint("team_id", "owner_email", "name", name="uq_team_owner_name_server"),
    )
    op.create_index("idx_servers_created_at_id", "servers", ["created_at", "id"], unique=False)
    op.create_table(
        "oauth_states",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("gateway_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=500), nullable=False),
        sa.Column("code_verifier", sa.String(length=128), nullable=True),
        sa.Column("app_user_email", sa.String(length=255), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["gateway_id"], ["gateways.id"], name=op.f("fk_oauth_states_gateway_id"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_states")),
        sa.UniqueConstraint("state", name=op.f("uq_oauth_states_state")),
    )
    op.create_index("idx_oauth_state_lookup", "oauth_states", ["gateway_id", "state"], unique=False)
    op.create_table(
        "oauth_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("gateway_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("app_user_email", sa.String(length=255), nullable=False),
        sa.Column("access_token", mcpgateway.db.EncryptedText(), nullable=False),
        sa.Column("refresh_token", mcpgateway.db.EncryptedText(), nullable=True),
        sa.Column("token_type", sa.String(length=50), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scopes", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["app_user_email"], ["email_users.email"], name=op.f("fk_oauth_tokens_app_user_email"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["gateway_id"], ["gateways.id"], name=op.f("fk_oauth_tokens_gateway_id"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_tokens")),
        sa.UniqueConstraint("gateway_id", "app_user_email", name="uq_oauth_gateway_user"),
    )
    op.create_table(
        "prompts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("custom_name", sa.String(length=255), nullable=False),
        sa.Column("custom_name_slug", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("template", sa.Text(), nullable=False),
        sa.Column("argument_schema", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("created_from_ip", sa.String(length=45), nullable=True),
        sa.Column("created_via", sa.String(length=100), nullable=True),
        sa.Column("created_user_agent", sa.Text(), nullable=True),
        sa.Column("modified_by", sa.String(length=255), nullable=True),
        sa.Column("modified_from_ip", sa.String(length=45), nullable=True),
        sa.Column("modified_via", sa.String(length=100), nullable=True),
        sa.Column("modified_user_agent", sa.Text(), nullable=True),
        sa.Column("import_batch_id", sa.String(length=36), nullable=True),
        sa.Column("federation_source", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("gateway_id", sa.String(length=36), nullable=True),
        sa.Column("team_id", sa.String(length=36), nullable=True),
        sa.Column("owner_email", sa.String(length=255), nullable=True),
        sa.Column("visibility", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(["gateway_id"], ["gateways.id"], name=op.f("fk_prompts_gateway_id"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["email_teams.id"], name=op.f("fk_prompts_team_id"), ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompts")),
        sa.UniqueConstraint("gateway_id", "original_name", name="uq_gateway_id__original_name_prompt"),
        sa.UniqueConstraint("team_id", "owner_email", "gateway_id", "name", name="uq_team_owner_gateway_name_prompt"),
    )
    op.create_index("idx_prompts_created_at_id", "prompts", ["created_at", "id"], unique=False)
    op.create_index(
        "uq_team_owner_name_prompt_local", "prompts", ["team_id", "owner_email", "name"], unique=True, postgresql_where=sa.text("gateway_id IS NULL"), sqlite_where=sa.text("gateway_id IS NULL")
    )
    op.create_table(
        "resources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("uri", sa.String(length=767), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("uri_template", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("created_from_ip", sa.String(length=45), nullable=True),
        sa.Column("created_via", sa.String(length=100), nullable=True),
        sa.Column("created_user_agent", sa.Text(), nullable=True),
        sa.Column("modified_by", sa.String(length=255), nullable=True),
        sa.Column("modified_from_ip", sa.String(length=45), nullable=True),
        sa.Column("modified_via", sa.String(length=100), nullable=True),
        sa.Column("modified_user_agent", sa.Text(), nullable=True),
        sa.Column("import_batch_id", sa.String(length=36), nullable=True),
        sa.Column("federation_source", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("text_content", sa.Text(), nullable=True),
        sa.Column("binary_content", sa.LargeBinary(), nullable=True),
        sa.Column("gateway_id", sa.String(length=36), nullable=True),
        sa.Column("team_id", sa.String(length=36), nullable=True),
        sa.Column("owner_email", sa.String(length=255), nullable=True),
        sa.Column("visibility", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(["gateway_id"], ["gateways.id"], name=op.f("fk_resources_gateway_id"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["email_teams.id"], name=op.f("fk_resources_team_id"), ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resources")),
        sa.UniqueConstraint("team_id", "owner_email", "gateway_id", "uri", name="uq_team_owner_gateway_uri_resource"),
    )
    op.create_index("idx_resources_created_at_id", "resources", ["created_at", "id"], unique=False)
    op.create_index(
        "uq_team_owner_uri_resource_local", "resources", ["team_id", "owner_email", "uri"], unique=True, postgresql_where=sa.text("gateway_id IS NULL"), sqlite_where=sa.text("gateway_id IS NULL")
    )
    op.create_table(
        "server_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.String(length=36), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("response_time", sa.Float(), nullable=False),
        sa.Column("is_success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["server_id"], ["servers.id"], name=op.f("fk_server_metrics_server_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_server_metrics")),
    )
    op.create_index(op.f("ix_server_metrics_server_id"), "server_metrics", ["server_id"], unique=False)
    op.create_index(op.f("ix_server_metrics_timestamp"), "server_metrics", ["timestamp"], unique=False)
    op.create_table(
        "tools",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=767), nullable=True),
        sa.Column("original_description", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("integration_type", sa.String(length=20), nullable=False),
        sa.Column("request_type", sa.String(length=20), nullable=False),
        sa.Column("headers", sa.JSON(), nullable=True),
        sa.Column("input_schema", sa.JSON(), nullable=False),
        sa.Column("output_schema", sa.JSON(), nullable=True),
        sa.Column("annotations", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("reachable", sa.Boolean(), nullable=False),
        sa.Column("jsonpath_filter", sa.Text(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("created_from_ip", sa.String(length=45), nullable=True),
        sa.Column("created_via", sa.String(length=100), nullable=True),
        sa.Column("created_user_agent", sa.Text(), nullable=True),
        sa.Column("modified_by", sa.String(length=255), nullable=True),
        sa.Column("modified_from_ip", sa.String(length=45), nullable=True),
        sa.Column("modified_via", sa.String(length=100), nullable=True),
        sa.Column("modified_user_agent", sa.Text(), nullable=True),
        sa.Column("import_batch_id", sa.String(length=36), nullable=True),
        sa.Column("federation_source", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("auth_type", sa.String(length=20), nullable=True),
        sa.Column("auth_value", sa.Text(), nullable=True),
        sa.Column("custom_name", sa.String(length=255), nullable=False),
        sa.Column("custom_name_slug", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("base_url", sa.String(), nullable=True),
        sa.Column("path_template", sa.String(), nullable=True),
        sa.Column("query_mapping", sa.JSON(), nullable=True),
        sa.Column("header_mapping", sa.JSON(), nullable=True),
        sa.Column("timeout_ms", sa.Integer(), nullable=True),
        sa.Column("expose_passthrough", sa.Boolean(), nullable=False),
        sa.Column("allowlist", sa.JSON(), nullable=True),
        sa.Column("plugin_chain_pre", sa.JSON(), nullable=True),
        sa.Column("plugin_chain_post", sa.JSON(), nullable=True),
        sa.Column("gateway_id", sa.String(length=36), nullable=True),
        sa.Column("grpc_service_id", sa.String(length=36), nullable=True),
        sa.Column("team_id", sa.String(length=36), nullable=True),
        sa.Column("owner_email", sa.String(length=255), nullable=True),
        sa.Column("visibility", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["gateway_id"], ["gateways.id"], name=op.f("fk_tools_gateway_id"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["grpc_service_id"], ["grpc_services.id"], name=op.f("fk_tools_grpc_service_id"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["email_teams.id"], name=op.f("fk_tools_team_id"), ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tools")),
        sa.UniqueConstraint("gateway_id", "original_name", name="uq_gateway_id__original_name"),
        sa.UniqueConstraint("team_id", "owner_email", "name", name="uq_team_owner_email_name_tool"),
    )
    op.create_index("idx_tools_created_at_id", "tools", ["created_at", "id"], unique=False)
    op.create_table(
        "prompt_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prompt_id", sa.String(length=36), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("response_time", sa.Float(), nullable=False),
        sa.Column("is_success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["prompt_id"], ["prompts.id"], name=op.f("fk_prompt_metrics_prompt_id"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_metrics")),
    )
    op.create_index(op.f("ix_prompt_metrics_prompt_id"), "prompt_metrics", ["prompt_id"], unique=False)
    op.create_index(op.f("ix_prompt_metrics_timestamp"), "prompt_metrics", ["timestamp"], unique=False)
    op.create_table(
        "resource_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("response_time", sa.Float(), nullable=False),
        sa.Column("is_success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["resource_id"], ["resources.id"], name=op.f("fk_resource_metrics_resource_id"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resource_metrics")),
    )
    op.create_index(op.f("ix_resource_metrics_resource_id"), "resource_metrics", ["resource_id"], unique=False)
    op.create_index(op.f("ix_resource_metrics_timestamp"), "resource_metrics", ["timestamp"], unique=False)
    op.create_table(
        "resource_subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=False),
        sa.Column("subscriber_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_notification", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["resource_id"], ["resources.id"], name=op.f("fk_resource_subscriptions_resource_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resource_subscriptions")),
    )
    op.create_table(
        "server_prompt_association",
        sa.Column("server_id", sa.String(length=36), nullable=False),
        sa.Column("prompt_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["prompt_id"], ["prompts.id"], name=op.f("fk_server_prompt_association_prompt_id"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["server_id"], ["servers.id"], name=op.f("fk_server_prompt_association_server_id"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("server_id", "prompt_id", name=op.f("pk_server_prompt_association")),
    )
    op.create_table(
        "server_resource_association",
        sa.Column("server_id", sa.String(length=36), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["resource_id"], ["resources.id"], name=op.f("fk_server_resource_association_resource_id"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["server_id"], ["servers.id"], name=op.f("fk_server_resource_association_server_id"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("server_id", "resource_id", name=op.f("pk_server_resource_association")),
    )
    op.create_table(
        "server_tool_association",
        sa.Column("server_id", sa.String(length=36), nullable=False),
        sa.Column("tool_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["server_id"], ["servers.id"], name=op.f("fk_server_tool_association_server_id"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tool_id"], ["tools.id"], name=op.f("fk_server_tool_association_tool_id"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("server_id", "tool_id", name=op.f("pk_server_tool_association")),
    )
    op.create_table(
        "tool_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tool_id", sa.String(length=36), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("response_time", sa.Float(), nullable=False),
        sa.Column("is_success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["tool_id"], ["tools.id"], name=op.f("fk_tool_metrics_tool_id"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_metrics")),
    )
    op.create_index(op.f("ix_tool_metrics_timestamp"), "tool_metrics", ["timestamp"], unique=False)
    op.create_index(op.f("ix_tool_metrics_tool_id"), "tool_metrics", ["tool_id"], unique=False)
    op.create_table(
        "server_a2a_association",
        sa.Column("server_id", sa.String(length=36), nullable=False),
        sa.Column("a2a_agent_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["a2a_agent_id"], ["a2a_agents.id"], name=op.f("fk_server_a2a_association_a2a_agent_id")),
        sa.ForeignKeyConstraint(["server_id"], ["servers.id"], name=op.f("fk_server_a2a_association_server_id")),
        sa.PrimaryKeyConstraint("server_id", "a2a_agent_id", name=op.f("pk_server_a2a_association")),
    )
    op.drop_index(op.f("idx_a2a_agent_metrics_a2a_agent_id"), table_name="a2a_agent_metrics")
    op.drop_index(op.f("idx_a2a_agent_metrics_agent_is_success"), table_name="a2a_agent_metrics")
    op.create_index(op.f("ix_a2a_agent_metrics_a2a_agent_id"), "a2a_agent_metrics", ["a2a_agent_id"], unique=False)
    op.create_index(op.f("ix_a2a_agent_metrics_timestamp"), "a2a_agent_metrics", ["timestamp"], unique=False)
    op.alter_column("a2a_agent_metrics_hourly", "created_at", existing_type=sa.DATETIME(), nullable=False, existing_server_default=sa.text("(CURRENT_TIMESTAMP)"))
    op.add_column("a2a_agents", sa.Column("tool_id", sa.String(length=36), nullable=True))
    op.alter_column("a2a_agents", "capabilities", existing_type=sqlite.JSON(), nullable=False)
    op.alter_column("a2a_agents", "config", existing_type=sqlite.JSON(), nullable=False)
    op.alter_column("a2a_agents", "auth_type", existing_type=sa.VARCHAR(length=50), type_=sa.String(length=20), existing_nullable=True)
    op.alter_column("a2a_agents", "enabled", existing_type=sa.BOOLEAN(), nullable=False, existing_server_default=sa.text("'1'"))
    op.alter_column("a2a_agents", "reachable", existing_type=sa.BOOLEAN(), nullable=False, existing_server_default=sa.text("'1'"))
    op.alter_column("a2a_agents", "tags", existing_type=sqlite.JSON(), nullable=False)
    op.drop_index(op.f("idx_a2a_agents_enabled"), table_name="a2a_agents")
    op.drop_index(op.f("idx_a2a_agents_name"), table_name="a2a_agents")
    op.drop_index(op.f("idx_a2a_agents_owner_visibility"), table_name="a2a_agents")
    op.drop_index(op.f("idx_a2a_agents_slug"), table_name="a2a_agents")
    op.drop_index(op.f("idx_a2a_agents_slug_visibility"), table_name="a2a_agents")
    op.drop_index(op.f("idx_a2a_agents_team_id"), table_name="a2a_agents")
    op.drop_index(op.f("idx_a2a_agents_team_visibility"), table_name="a2a_agents")
    op.drop_index(op.f("idx_a2a_agents_team_visibility_active_created"), table_name="a2a_agents")
    op.drop_index(op.f("idx_a2a_agents_visibility"), table_name="a2a_agents")
    op.drop_index(op.f("idx_a2a_agents_visibility_active_created"), table_name="a2a_agents")
    op.drop_index(op.f("ix_a2a_agents_uaid"), table_name="a2a_agents")
    op.drop_constraint(op.f("uq_team_owner_slug_a2a_agents"), "a2a_agents", type_="unique")
    op.create_index("idx_a2a_agents_tool_id", "a2a_agents", ["tool_id"], unique=False)
    op.create_unique_constraint("uq_team_owner_slug_a2a_agent", "a2a_agents", ["team_id", "owner_email", "slug"])
    op.create_foreign_key(op.f("fk_a2a_agents_team_id"), "a2a_agents", "email_teams", ["team_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(op.f("fk_a2a_agents_tool_id"), "a2a_agents", "tools", ["tool_id"], ["id"], ondelete="SET NULL")
    op.drop_index(op.f("ix_a2a_task_events_agent_id"), table_name="a2a_task_events")
    op.create_index(op.f("ix_a2a_task_events_a2a_agent_id"), "a2a_task_events", ["a2a_agent_id"], unique=False)
    op.alter_column("audit_trails", "resource_id", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.drop_index(op.f("idx_audit_trails_action"), table_name="audit_trails")
    op.drop_index(op.f("idx_audit_trails_correlation_id"), table_name="audit_trails")
    op.drop_index(op.f("idx_audit_trails_data_classification"), table_name="audit_trails")
    op.drop_index(op.f("idx_audit_trails_request_id"), table_name="audit_trails")
    op.drop_index(op.f("idx_audit_trails_requires_review"), table_name="audit_trails")
    op.drop_index(op.f("idx_audit_trails_resource_id"), table_name="audit_trails")
    op.drop_index(op.f("idx_audit_trails_resource_type"), table_name="audit_trails")
    op.drop_index(op.f("idx_audit_trails_success"), table_name="audit_trails")
    op.drop_index(op.f("idx_audit_trails_team_id"), table_name="audit_trails")
    op.drop_index(op.f("idx_audit_trails_timestamp"), table_name="audit_trails")
    op.drop_index(op.f("idx_audit_trails_user_email"), table_name="audit_trails")
    op.drop_index(op.f("idx_audit_trails_user_id"), table_name="audit_trails")
    op.create_index(op.f("ix_audit_trails_action"), "audit_trails", ["action"], unique=False)
    op.create_index(op.f("ix_audit_trails_correlation_id"), "audit_trails", ["correlation_id"], unique=False)
    op.create_index(op.f("ix_audit_trails_data_classification"), "audit_trails", ["data_classification"], unique=False)
    op.create_index(op.f("ix_audit_trails_request_id"), "audit_trails", ["request_id"], unique=False)
    op.create_index(op.f("ix_audit_trails_requires_review"), "audit_trails", ["requires_review"], unique=False)
    op.create_index(op.f("ix_audit_trails_resource_id"), "audit_trails", ["resource_id"], unique=False)
    op.create_index(op.f("ix_audit_trails_resource_type"), "audit_trails", ["resource_type"], unique=False)
    op.create_index(op.f("ix_audit_trails_success"), "audit_trails", ["success"], unique=False)
    op.create_index(op.f("ix_audit_trails_team_id"), "audit_trails", ["team_id"], unique=False)
    op.create_index(op.f("ix_audit_trails_timestamp"), "audit_trails", ["timestamp"], unique=False)
    op.create_index(op.f("ix_audit_trails_user_email"), "audit_trails", ["user_email"], unique=False)
    op.create_index(op.f("ix_audit_trails_user_id"), "audit_trails", ["user_id"], unique=False)
    op.drop_index(op.f("idx_email_api_tokens_last_used"), table_name="email_api_tokens")
    op.drop_index(op.f("idx_email_api_tokens_server_id"), table_name="email_api_tokens")
    op.drop_index(op.f("idx_email_api_tokens_team_active_created"), table_name="email_api_tokens")
    op.drop_index(op.f("idx_email_api_tokens_team_id"), table_name="email_api_tokens")
    op.drop_index(op.f("idx_email_api_tokens_user_active_created"), table_name="email_api_tokens")
    op.create_index("idx_email_api_tokens_jti", "email_api_tokens", ["jti"], unique=False)
    op.create_index(op.f("ix_email_api_tokens_team_id"), "email_api_tokens", ["team_id"], unique=False)
    op.create_index(op.f("ix_email_api_tokens_user_email"), "email_api_tokens", ["user_email"], unique=False)
    op.create_foreign_key(op.f("fk_email_api_tokens_team_id"), "email_api_tokens", "email_teams", ["team_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(op.f("fk_email_api_tokens_server_id"), "email_api_tokens", "servers", ["server_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(op.f("fk_email_api_tokens_user_email"), "email_api_tokens", "email_users", ["user_email"], ["email"], ondelete="CASCADE")
    op.drop_index(op.f("idx_email_auth_events_event_type"), table_name="email_auth_events")
    op.drop_index(op.f("idx_email_auth_events_ip_address"), table_name="email_auth_events")
    op.drop_index(op.f("idx_email_auth_events_ip_time"), table_name="email_auth_events")
    op.drop_index(op.f("idx_email_auth_events_success"), table_name="email_auth_events")
    op.drop_index(op.f("idx_email_auth_events_success_time"), table_name="email_auth_events")
    op.drop_index(op.f("idx_email_auth_events_timestamp"), table_name="email_auth_events")
    op.drop_index(op.f("idx_email_auth_events_type_success_time"), table_name="email_auth_events")
    op.drop_index(op.f("idx_email_auth_events_user_email"), table_name="email_auth_events")
    op.drop_index(op.f("idx_email_auth_events_user_type_time"), table_name="email_auth_events")
    op.create_index(op.f("ix_email_auth_events_user_email"), "email_auth_events", ["user_email"], unique=False)
    op.drop_index(op.f("idx_email_team_invitations_email_active_created"), table_name="email_team_invitations")
    op.drop_index(op.f("idx_email_team_invitations_invited_by"), table_name="email_team_invitations")
    op.drop_index(op.f("idx_email_team_invitations_team_active_created"), table_name="email_team_invitations")
    op.drop_index(op.f("idx_email_team_invitations_team_id"), table_name="email_team_invitations")
    op.create_foreign_key(op.f("fk_email_team_invitations_invited_by"), "email_team_invitations", "email_users", ["invited_by"], ["email"])
    op.create_foreign_key(op.f("fk_email_team_invitations_team_id"), "email_team_invitations", "email_teams", ["team_id"], ["id"], ondelete="CASCADE")
    op.drop_index(op.f("idx_email_team_join_requests_reviewed_by"), table_name="email_team_join_requests")
    op.drop_index(op.f("idx_email_team_join_requests_team_id"), table_name="email_team_join_requests")
    op.drop_index(op.f("idx_email_team_join_requests_team_status_time"), table_name="email_team_join_requests")
    op.drop_index(op.f("idx_email_team_join_requests_user_email"), table_name="email_team_join_requests")
    op.drop_index(op.f("idx_email_team_join_requests_user_status_time"), table_name="email_team_join_requests")
    op.create_foreign_key(op.f("fk_email_team_join_requests_reviewed_by"), "email_team_join_requests", "email_users", ["reviewed_by"], ["email"])
    op.create_foreign_key(op.f("fk_email_team_join_requests_user_email"), "email_team_join_requests", "email_users", ["user_email"], ["email"])
    op.create_foreign_key(op.f("fk_email_team_join_requests_team_id"), "email_team_join_requests", "email_teams", ["team_id"], ["id"], ondelete="CASCADE")
    op.drop_index(op.f("idx_email_team_member_history_action_by"), table_name="email_team_member_history")
    op.drop_index(op.f("idx_email_team_member_history_team_id"), table_name="email_team_member_history")
    op.drop_index(op.f("idx_email_team_member_history_team_member_id"), table_name="email_team_member_history")
    op.drop_index(op.f("idx_email_team_member_history_user_email"), table_name="email_team_member_history")
    op.drop_constraint(op.f("fk_email_team_member_history_team_member_id"), "email_team_member_history", type_="foreignkey")
    op.create_foreign_key(op.f("fk_email_team_member_history_team_member_id"), "email_team_member_history", "email_team_members", ["team_member_id"], ["id"], ondelete="CASCADE")
    op.drop_index(op.f("idx_email_team_members_invited_by"), table_name="email_team_members")
    op.drop_index(op.f("idx_email_team_members_team_active_count"), table_name="email_team_members")
    op.drop_index(op.f("idx_email_team_members_team_id"), table_name="email_team_members")
    op.drop_index(op.f("idx_email_team_members_team_role_active"), table_name="email_team_members")
    op.drop_index(op.f("idx_email_team_members_user_email"), table_name="email_team_members")
    op.drop_index(op.f("idx_email_team_members_user_team_active"), table_name="email_team_members")
    op.create_foreign_key(op.f("fk_email_team_members_team_id"), "email_team_members", "email_teams", ["team_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(op.f("fk_email_team_members_invited_by"), "email_team_members", "email_users", ["invited_by"], ["email"])
    op.create_foreign_key(op.f("fk_email_team_members_user_email"), "email_team_members", "email_users", ["user_email"], ["email"])
    op.drop_index(op.f("idx_email_teams_created_by"), table_name="email_teams")
    op.drop_index(op.f("idx_email_teams_creator_personal_active"), table_name="email_teams")
    op.drop_index(op.f("idx_email_teams_visibility_active_created"), table_name="email_teams")
    op.create_foreign_key(op.f("fk_email_teams_created_by"), "email_teams", "email_users", ["created_by"], ["email"])
    op.drop_index(op.f("idx_email_users_email"), table_name="email_users")
    op.create_index(op.f("ix_email_users_email"), "email_users", ["email"], unique=False)
    op.alter_column("grpc_services", "grpc_metadata", existing_type=sqlite.JSON(), nullable=False)
    op.alter_column("grpc_services", "discovered_services", existing_type=sqlite.JSON(), nullable=False)
    op.alter_column("grpc_services", "tags", existing_type=sqlite.JSON(), nullable=False)
    op.drop_index(op.f("idx_grpc_services_name"), table_name="grpc_services")
    op.drop_index(op.f("idx_grpc_services_slug"), table_name="grpc_services")
    op.drop_index(op.f("idx_grpc_services_team_id"), table_name="grpc_services")
    op.create_unique_constraint(op.f("uq_grpc_services_name"), "grpc_services", ["name"])
    op.create_unique_constraint(op.f("uq_grpc_services_slug"), "grpc_services", ["slug"])
    op.drop_index(op.f("idx_observability_events_span_id_timestamp"), table_name="observability_events")
    op.create_index(op.f("ix_observability_events_severity"), "observability_events", ["severity"], unique=False)
    op.create_index(op.f("ix_observability_events_span_id"), "observability_events", ["span_id"], unique=False)
    op.create_index(op.f("ix_observability_events_timestamp"), "observability_events", ["timestamp"], unique=False)
    op.create_index(op.f("ix_observability_metrics_name"), "observability_metrics", ["name"], unique=False)
    op.create_index(op.f("ix_observability_metrics_resource_id"), "observability_metrics", ["resource_id"], unique=False)
    op.create_index(op.f("ix_observability_metrics_resource_type"), "observability_metrics", ["resource_type"], unique=False)
    op.create_index(op.f("ix_observability_metrics_timestamp"), "observability_metrics", ["timestamp"], unique=False)
    op.create_index(op.f("ix_observability_metrics_trace_id"), "observability_metrics", ["trace_id"], unique=False)
    op.drop_index(op.f("idx_observability_saved_queries_name"), table_name="observability_saved_queries")
    op.create_index(op.f("ix_observability_saved_queries_name"), "observability_saved_queries", ["name"], unique=False)
    op.create_index(op.f("ix_observability_saved_queries_user_email"), "observability_saved_queries", ["user_email"], unique=False)
    op.drop_index(op.f("idx_observability_spans_duration_ms"), table_name="observability_spans")
    op.drop_index(op.f("idx_observability_spans_kind_status"), table_name="observability_spans")
    op.drop_index(op.f("idx_observability_spans_name"), table_name="observability_spans")
    op.drop_index(op.f("idx_observability_spans_resource_status_time"), table_name="observability_spans")
    op.drop_index(op.f("idx_observability_spans_resource_type_start_time"), table_name="observability_spans")
    op.drop_index(op.f("idx_observability_spans_trace_id_start_time"), table_name="observability_spans")
    op.drop_index(op.f("idx_observability_spans_trace_resource_time"), table_name="observability_spans")
    op.create_index(op.f("ix_observability_spans_parent_span_id"), "observability_spans", ["parent_span_id"], unique=False)
    op.create_index(op.f("ix_observability_spans_resource_id"), "observability_spans", ["resource_id"], unique=False)
    op.create_index(op.f("ix_observability_spans_resource_name"), "observability_spans", ["resource_name"], unique=False)
    op.create_index(op.f("ix_observability_spans_resource_type"), "observability_spans", ["resource_type"], unique=False)
    op.create_index(op.f("ix_observability_spans_start_time"), "observability_spans", ["start_time"], unique=False)
    op.create_index(op.f("ix_observability_spans_trace_id"), "observability_spans", ["trace_id"], unique=False)
    op.drop_index(op.f("idx_observability_traces_duration_ms"), table_name="observability_traces")
    op.drop_index(op.f("idx_observability_traces_http_method_start_time"), table_name="observability_traces")
    op.drop_index(op.f("idx_observability_traces_name"), table_name="observability_traces")
    op.drop_index(op.f("idx_observability_traces_status_method_time"), table_name="observability_traces")
    op.drop_index(op.f("idx_observability_traces_status_start_time"), table_name="observability_traces")
    op.drop_index(op.f("idx_observability_traces_user_status_time"), table_name="observability_traces")
    op.create_index(op.f("ix_observability_traces_start_time"), "observability_traces", ["start_time"], unique=False)
    op.create_index(op.f("ix_observability_traces_user_email"), "observability_traces", ["user_email"], unique=False)
    op.drop_constraint(op.f("uq_password_reset_tokens_token_hash"), "password_reset_tokens", type_="unique")
    op.drop_index(op.f("idx_pending_user_approvals_approved_by"), table_name="pending_user_approvals")
    op.drop_index(op.f("idx_pending_user_approvals_email"), table_name="pending_user_approvals")
    op.create_foreign_key(op.f("fk_pending_user_approvals_approved_by"), "pending_user_approvals", "email_users", ["approved_by"], ["email"])
    op.create_index(op.f("ix_performance_aggregates_host"), "performance_aggregates", ["host"], unique=False)
    op.create_index(op.f("ix_performance_aggregates_period_start"), "performance_aggregates", ["period_start"], unique=False)
    op.create_index(op.f("ix_performance_aggregates_period_type"), "performance_aggregates", ["period_type"], unique=False)
    op.drop_index(op.f("idx_performance_metrics_component"), table_name="performance_metrics")
    op.drop_index(op.f("idx_performance_metrics_operation_type"), table_name="performance_metrics")
    op.drop_index(op.f("idx_performance_metrics_timestamp"), table_name="performance_metrics")
    op.drop_index(op.f("idx_performance_metrics_window_start"), table_name="performance_metrics")
    op.create_index(op.f("ix_performance_metrics_component"), "performance_metrics", ["component"], unique=False)
    op.create_index(op.f("ix_performance_metrics_operation_type"), "performance_metrics", ["operation_type"], unique=False)
    op.create_index(op.f("ix_performance_metrics_timestamp"), "performance_metrics", ["timestamp"], unique=False)
    op.create_index(op.f("ix_performance_metrics_window_start"), "performance_metrics", ["window_start"], unique=False)
    op.create_index(op.f("ix_performance_snapshots_host"), "performance_snapshots", ["host"], unique=False)
    op.create_index(op.f("ix_performance_snapshots_timestamp"), "performance_snapshots", ["timestamp"], unique=False)
    op.create_index(op.f("ix_performance_snapshots_worker_id"), "performance_snapshots", ["worker_id"], unique=False)
    op.drop_index(op.f("idx_permission_audit_log_granted"), table_name="permission_audit_log")
    op.drop_index(op.f("idx_permission_audit_log_permission"), table_name="permission_audit_log")
    op.drop_index(op.f("idx_permission_audit_log_resource_granted_time"), table_name="permission_audit_log")
    op.drop_index(op.f("idx_permission_audit_log_resource_type"), table_name="permission_audit_log")
    op.drop_index(op.f("idx_permission_audit_log_team_id"), table_name="permission_audit_log")
    op.drop_index(op.f("idx_permission_audit_log_team_time"), table_name="permission_audit_log")
    op.drop_index(op.f("idx_permission_audit_log_timestamp"), table_name="permission_audit_log")
    op.drop_index(op.f("idx_permission_audit_log_user_email"), table_name="permission_audit_log")
    op.drop_index(op.f("idx_permission_audit_log_user_time"), table_name="permission_audit_log")
    op.alter_column("prompt_metrics_hourly", "created_at", existing_type=sa.DATETIME(), nullable=False, existing_server_default=sa.text("(CURRENT_TIMESTAMP)"))
    op.alter_column("registered_oauth_clients", "token_endpoint_auth_method", existing_type=sa.VARCHAR(length=50), nullable=False, existing_server_default=sa.text("'client_secret_basic'"))
    op.alter_column("registered_oauth_clients", "is_active", existing_type=sa.BOOLEAN(), nullable=False, existing_server_default=sa.text("1"))
    op.drop_index(op.f("idx_registered_oauth_clients_gateway_id"), table_name="registered_oauth_clients")
    op.create_index(op.f("ix_registered_oauth_clients_gateway_id"), "registered_oauth_clients", ["gateway_id"], unique=False)
    op.alter_column("resource_metrics_hourly", "created_at", existing_type=sa.DATETIME(), nullable=False, existing_server_default=sa.text("(CURRENT_TIMESTAMP)"))
    op.drop_index(op.f("idx_roles_created_by"), table_name="roles")
    op.drop_index(op.f("idx_roles_inherits_from"), table_name="roles")
    op.create_foreign_key(op.f("fk_roles_inherits_from"), "roles", "roles", ["inherits_from"], ["id"])
    op.create_foreign_key(op.f("fk_roles_created_by"), "roles", "email_users", ["created_by"], ["email"])
    op.drop_index(op.f("idx_security_events_category"), table_name="security_events")
    op.drop_index(op.f("idx_security_events_client_ip"), table_name="security_events")
    op.drop_index(op.f("idx_security_events_correlation_id"), table_name="security_events")
    op.drop_index(op.f("idx_security_events_detected_at"), table_name="security_events")
    op.drop_index(op.f("idx_security_events_event_type"), table_name="security_events")
    op.drop_index(op.f("idx_security_events_log_entry_id"), table_name="security_events")
    op.drop_index(op.f("idx_security_events_resolved"), table_name="security_events")
    op.drop_index(op.f("idx_security_events_severity"), table_name="security_events")
    op.drop_index(op.f("idx_security_events_timestamp"), table_name="security_events")
    op.drop_index(op.f("idx_security_events_user_email"), table_name="security_events")
    op.drop_index(op.f("idx_security_events_user_id"), table_name="security_events")
    op.create_index(op.f("ix_security_events_category"), "security_events", ["category"], unique=False)
    op.create_index(op.f("ix_security_events_client_ip"), "security_events", ["client_ip"], unique=False)
    op.create_index(op.f("ix_security_events_correlation_id"), "security_events", ["correlation_id"], unique=False)
    op.create_index(op.f("ix_security_events_event_type"), "security_events", ["event_type"], unique=False)
    op.create_index(op.f("ix_security_events_log_entry_id"), "security_events", ["log_entry_id"], unique=False)
    op.create_index(op.f("ix_security_events_resolved"), "security_events", ["resolved"], unique=False)
    op.create_index(op.f("ix_security_events_severity"), "security_events", ["severity"], unique=False)
    op.create_index(op.f("ix_security_events_timestamp"), "security_events", ["timestamp"], unique=False)
    op.create_index(op.f("ix_security_events_user_email"), "security_events", ["user_email"], unique=False)
    op.create_index(op.f("ix_security_events_user_id"), "security_events", ["user_id"], unique=False)
    op.alter_column("server_metrics_hourly", "created_at", existing_type=sa.DATETIME(), nullable=False, existing_server_default=sa.text("(CURRENT_TIMESTAMP)"))
    op.drop_index(op.f("idx_sso_auth_sessions_provider_id"), table_name="sso_auth_sessions")
    op.drop_index(op.f("idx_sso_auth_sessions_provider_user_created"), table_name="sso_auth_sessions")
    op.drop_index(op.f("idx_sso_auth_sessions_user_email"), table_name="sso_auth_sessions")
    op.create_foreign_key(op.f("fk_sso_auth_sessions_provider_id"), "sso_auth_sessions", "sso_providers", ["provider_id"], ["id"])
    op.create_foreign_key(op.f("fk_sso_auth_sessions_user_email"), "sso_auth_sessions", "email_users", ["user_email"], ["email"])
    op.alter_column("sso_providers", "trusted_domains", existing_type=sqlite.JSON(), nullable=False)
    op.alter_column("sso_providers", "team_mapping", existing_type=sqlite.JSON(), nullable=False)
    op.drop_index(op.f("idx_structured_log_entries_component"), table_name="structured_log_entries")
    op.drop_index(op.f("idx_structured_log_entries_correlation_id"), table_name="structured_log_entries")
    op.drop_index(op.f("idx_structured_log_entries_is_security_event"), table_name="structured_log_entries")
    op.drop_index(op.f("idx_structured_log_entries_level"), table_name="structured_log_entries")
    op.drop_index(op.f("idx_structured_log_entries_operation_type"), table_name="structured_log_entries")
    op.drop_index(op.f("idx_structured_log_entries_request_id"), table_name="structured_log_entries")
    op.drop_index(op.f("idx_structured_log_entries_security_severity"), table_name="structured_log_entries")
    op.drop_index(op.f("idx_structured_log_entries_timestamp"), table_name="structured_log_entries")
    op.drop_index(op.f("idx_structured_log_entries_trace_id"), table_name="structured_log_entries")
    op.drop_index(op.f("idx_structured_log_entries_user_email"), table_name="structured_log_entries")
    op.drop_index(op.f("idx_structured_log_entries_user_id"), table_name="structured_log_entries")
    op.create_index(op.f("ix_structured_log_entries_component"), "structured_log_entries", ["component"], unique=False)
    op.create_index(op.f("ix_structured_log_entries_correlation_id"), "structured_log_entries", ["correlation_id"], unique=False)
    op.create_index(op.f("ix_structured_log_entries_is_security_event"), "structured_log_entries", ["is_security_event"], unique=False)
    op.create_index(op.f("ix_structured_log_entries_level"), "structured_log_entries", ["level"], unique=False)
    op.create_index(op.f("ix_structured_log_entries_operation_type"), "structured_log_entries", ["operation_type"], unique=False)
    op.create_index(op.f("ix_structured_log_entries_request_id"), "structured_log_entries", ["request_id"], unique=False)
    op.create_index(op.f("ix_structured_log_entries_security_severity"), "structured_log_entries", ["security_severity"], unique=False)
    op.create_index(op.f("ix_structured_log_entries_timestamp"), "structured_log_entries", ["timestamp"], unique=False)
    op.create_index(op.f("ix_structured_log_entries_trace_id"), "structured_log_entries", ["trace_id"], unique=False)
    op.create_index(op.f("ix_structured_log_entries_user_email"), "structured_log_entries", ["user_email"], unique=False)
    op.create_index(op.f("ix_structured_log_entries_user_id"), "structured_log_entries", ["user_id"], unique=False)
    op.drop_index(op.f("idx_token_revocations_revoked_by"), table_name="token_revocations")
    op.create_index(op.f("ix_token_revocations_revoked_at"), "token_revocations", ["revoked_at"], unique=False)
    op.create_index(op.f("ix_token_revocations_token_expiry"), "token_revocations", ["token_expiry"], unique=False)
    op.create_foreign_key(op.f("fk_token_revocations_revoked_by"), "token_revocations", "email_users", ["revoked_by"], ["email"])
    op.alter_column("token_usage_logs", "id", existing_type=sa.BIGINT(), type_=sa.Integer(), existing_nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_token_usage_logs_timestamp"), table_name="token_usage_logs")
    op.drop_index(op.f("idx_token_usage_logs_token_jti"), table_name="token_usage_logs")
    op.drop_index(op.f("idx_token_usage_logs_user_email"), table_name="token_usage_logs")
    op.create_index(op.f("ix_token_usage_logs_timestamp"), "token_usage_logs", ["timestamp"], unique=False)
    op.create_index(op.f("ix_token_usage_logs_token_jti"), "token_usage_logs", ["token_jti"], unique=False)
    op.create_index(op.f("ix_token_usage_logs_user_email"), "token_usage_logs", ["user_email"], unique=False)
    op.alter_column("tool_metrics_hourly", "created_at", existing_type=sa.DATETIME(), nullable=False, existing_server_default=sa.text("(CURRENT_TIMESTAMP)"))
    op.alter_column("toolops_test_cases", "test_cases", existing_type=sqlite.JSON(), nullable=False)
    op.alter_column("toolops_test_cases", "run_status", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.drop_index(op.f("idx_user_roles_granted_by"), table_name="user_roles")
    op.drop_index(op.f("idx_user_roles_role_id"), table_name="user_roles")
    op.drop_index(op.f("idx_user_roles_role_scope_active"), table_name="user_roles")
    op.drop_index(op.f("idx_user_roles_scope"), table_name="user_roles")
    op.drop_index(op.f("idx_user_roles_scope_id"), table_name="user_roles")
    op.drop_index(op.f("idx_user_roles_user_email"), table_name="user_roles")
    op.drop_index(op.f("idx_user_roles_user_scope_active"), table_name="user_roles")
    op.create_foreign_key(op.f("fk_user_roles_role_id"), "user_roles", "roles", ["role_id"], ["id"])
    op.create_foreign_key(op.f("fk_user_roles_granted_by"), "user_roles", "email_users", ["granted_by"], ["email"])
    op.create_foreign_key(op.f("fk_user_roles_user_email"), "user_roles", "email_users", ["user_email"], ["email"])
    op.drop_column("user_roles", "migration_source")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_roles", sa.Column("migration_source", sa.VARCHAR(length=50), nullable=True))
    op.drop_constraint(op.f("fk_user_roles_user_email"), "user_roles", type_="foreignkey")
    op.drop_constraint(op.f("fk_user_roles_granted_by"), "user_roles", type_="foreignkey")
    op.drop_constraint(op.f("fk_user_roles_role_id"), "user_roles", type_="foreignkey")
    op.create_index(op.f("idx_user_roles_user_scope_active"), "user_roles", ["user_email", "scope", "is_active"], unique=False)
    op.create_index(op.f("idx_user_roles_user_email"), "user_roles", ["user_email"], unique=False)
    op.create_index(op.f("idx_user_roles_scope_id"), "user_roles", ["scope_id"], unique=False)
    op.create_index(op.f("idx_user_roles_scope"), "user_roles", ["scope"], unique=False)
    op.create_index(op.f("idx_user_roles_role_scope_active"), "user_roles", ["role_id", "scope", "is_active"], unique=False)
    op.create_index(op.f("idx_user_roles_role_id"), "user_roles", ["role_id"], unique=False)
    op.create_index(op.f("idx_user_roles_granted_by"), "user_roles", ["granted_by"], unique=False)
    op.alter_column("toolops_test_cases", "run_status", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column("toolops_test_cases", "test_cases", existing_type=sqlite.JSON(), nullable=True)
    op.alter_column("tool_metrics_hourly", "created_at", existing_type=sa.DATETIME(), nullable=True, existing_server_default=sa.text("(CURRENT_TIMESTAMP)"))
    op.drop_index(op.f("ix_token_usage_logs_user_email"), table_name="token_usage_logs")
    op.drop_index(op.f("ix_token_usage_logs_token_jti"), table_name="token_usage_logs")
    op.drop_index(op.f("ix_token_usage_logs_timestamp"), table_name="token_usage_logs")
    op.create_index(op.f("idx_token_usage_logs_user_email"), "token_usage_logs", ["user_email"], unique=False)
    op.create_index(op.f("idx_token_usage_logs_token_jti"), "token_usage_logs", ["token_jti"], unique=False)
    op.create_index(op.f("idx_token_usage_logs_timestamp"), "token_usage_logs", ["timestamp"], unique=False)
    op.alter_column("token_usage_logs", "id", existing_type=sa.Integer(), type_=sa.BIGINT(), existing_nullable=False, autoincrement=True)
    op.drop_constraint(op.f("fk_token_revocations_revoked_by"), "token_revocations", type_="foreignkey")
    op.drop_index(op.f("ix_token_revocations_token_expiry"), table_name="token_revocations")
    op.drop_index(op.f("ix_token_revocations_revoked_at"), table_name="token_revocations")
    op.create_index(op.f("idx_token_revocations_revoked_by"), "token_revocations", ["revoked_by"], unique=False)
    op.drop_index(op.f("ix_structured_log_entries_user_id"), table_name="structured_log_entries")
    op.drop_index(op.f("ix_structured_log_entries_user_email"), table_name="structured_log_entries")
    op.drop_index(op.f("ix_structured_log_entries_trace_id"), table_name="structured_log_entries")
    op.drop_index(op.f("ix_structured_log_entries_timestamp"), table_name="structured_log_entries")
    op.drop_index(op.f("ix_structured_log_entries_security_severity"), table_name="structured_log_entries")
    op.drop_index(op.f("ix_structured_log_entries_request_id"), table_name="structured_log_entries")
    op.drop_index(op.f("ix_structured_log_entries_operation_type"), table_name="structured_log_entries")
    op.drop_index(op.f("ix_structured_log_entries_level"), table_name="structured_log_entries")
    op.drop_index(op.f("ix_structured_log_entries_is_security_event"), table_name="structured_log_entries")
    op.drop_index(op.f("ix_structured_log_entries_correlation_id"), table_name="structured_log_entries")
    op.drop_index(op.f("ix_structured_log_entries_component"), table_name="structured_log_entries")
    op.create_index(op.f("idx_structured_log_entries_user_id"), "structured_log_entries", ["user_id"], unique=False)
    op.create_index(op.f("idx_structured_log_entries_user_email"), "structured_log_entries", ["user_email"], unique=False)
    op.create_index(op.f("idx_structured_log_entries_trace_id"), "structured_log_entries", ["trace_id"], unique=False)
    op.create_index(op.f("idx_structured_log_entries_timestamp"), "structured_log_entries", ["timestamp"], unique=False)
    op.create_index(op.f("idx_structured_log_entries_security_severity"), "structured_log_entries", ["security_severity"], unique=False)
    op.create_index(op.f("idx_structured_log_entries_request_id"), "structured_log_entries", ["request_id"], unique=False)
    op.create_index(op.f("idx_structured_log_entries_operation_type"), "structured_log_entries", ["operation_type"], unique=False)
    op.create_index(op.f("idx_structured_log_entries_level"), "structured_log_entries", ["level"], unique=False)
    op.create_index(op.f("idx_structured_log_entries_is_security_event"), "structured_log_entries", ["is_security_event"], unique=False)
    op.create_index(op.f("idx_structured_log_entries_correlation_id"), "structured_log_entries", ["correlation_id"], unique=False)
    op.create_index(op.f("idx_structured_log_entries_component"), "structured_log_entries", ["component"], unique=False)
    op.alter_column("sso_providers", "team_mapping", existing_type=sqlite.JSON(), nullable=True)
    op.alter_column("sso_providers", "trusted_domains", existing_type=sqlite.JSON(), nullable=True)
    op.drop_constraint(op.f("fk_sso_auth_sessions_user_email"), "sso_auth_sessions", type_="foreignkey")
    op.drop_constraint(op.f("fk_sso_auth_sessions_provider_id"), "sso_auth_sessions", type_="foreignkey")
    op.create_index(op.f("idx_sso_auth_sessions_user_email"), "sso_auth_sessions", ["user_email"], unique=False)
    op.create_index(op.f("idx_sso_auth_sessions_provider_user_created"), "sso_auth_sessions", ["provider_id", "user_email", "created_at"], unique=False)
    op.create_index(op.f("idx_sso_auth_sessions_provider_id"), "sso_auth_sessions", ["provider_id"], unique=False)
    op.alter_column("server_metrics_hourly", "created_at", existing_type=sa.DATETIME(), nullable=True, existing_server_default=sa.text("(CURRENT_TIMESTAMP)"))
    op.drop_index(op.f("ix_security_events_user_id"), table_name="security_events")
    op.drop_index(op.f("ix_security_events_user_email"), table_name="security_events")
    op.drop_index(op.f("ix_security_events_timestamp"), table_name="security_events")
    op.drop_index(op.f("ix_security_events_severity"), table_name="security_events")
    op.drop_index(op.f("ix_security_events_resolved"), table_name="security_events")
    op.drop_index(op.f("ix_security_events_log_entry_id"), table_name="security_events")
    op.drop_index(op.f("ix_security_events_event_type"), table_name="security_events")
    op.drop_index(op.f("ix_security_events_correlation_id"), table_name="security_events")
    op.drop_index(op.f("ix_security_events_client_ip"), table_name="security_events")
    op.drop_index(op.f("ix_security_events_category"), table_name="security_events")
    op.create_index(op.f("idx_security_events_user_id"), "security_events", ["user_id"], unique=False)
    op.create_index(op.f("idx_security_events_user_email"), "security_events", ["user_email"], unique=False)
    op.create_index(op.f("idx_security_events_timestamp"), "security_events", ["timestamp"], unique=False)
    op.create_index(op.f("idx_security_events_severity"), "security_events", ["severity"], unique=False)
    op.create_index(op.f("idx_security_events_resolved"), "security_events", ["resolved"], unique=False)
    op.create_index(op.f("idx_security_events_log_entry_id"), "security_events", ["log_entry_id"], unique=False)
    op.create_index(op.f("idx_security_events_event_type"), "security_events", ["event_type"], unique=False)
    op.create_index(op.f("idx_security_events_detected_at"), "security_events", ["detected_at"], unique=False)
    op.create_index(op.f("idx_security_events_correlation_id"), "security_events", ["correlation_id"], unique=False)
    op.create_index(op.f("idx_security_events_client_ip"), "security_events", ["client_ip"], unique=False)
    op.create_index(op.f("idx_security_events_category"), "security_events", ["category"], unique=False)
    op.drop_constraint(op.f("fk_roles_created_by"), "roles", type_="foreignkey")
    op.drop_constraint(op.f("fk_roles_inherits_from"), "roles", type_="foreignkey")
    op.create_index(op.f("idx_roles_inherits_from"), "roles", ["inherits_from"], unique=False)
    op.create_index(op.f("idx_roles_created_by"), "roles", ["created_by"], unique=False)
    op.alter_column("resource_metrics_hourly", "created_at", existing_type=sa.DATETIME(), nullable=True, existing_server_default=sa.text("(CURRENT_TIMESTAMP)"))
    op.drop_index(op.f("ix_registered_oauth_clients_gateway_id"), table_name="registered_oauth_clients")
    op.create_index(op.f("idx_registered_oauth_clients_gateway_id"), "registered_oauth_clients", ["gateway_id"], unique=False)
    op.alter_column("registered_oauth_clients", "is_active", existing_type=sa.BOOLEAN(), nullable=True, existing_server_default=sa.text("1"))
    op.alter_column("registered_oauth_clients", "token_endpoint_auth_method", existing_type=sa.VARCHAR(length=50), nullable=True, existing_server_default=sa.text("'client_secret_basic'"))
    op.alter_column("prompt_metrics_hourly", "created_at", existing_type=sa.DATETIME(), nullable=True, existing_server_default=sa.text("(CURRENT_TIMESTAMP)"))
    op.create_index(op.f("idx_permission_audit_log_user_time"), "permission_audit_log", ["user_email", "timestamp"], unique=False)
    op.create_index(op.f("idx_permission_audit_log_user_email"), "permission_audit_log", ["user_email"], unique=False)
    op.create_index(op.f("idx_permission_audit_log_timestamp"), "permission_audit_log", ["timestamp"], unique=False)
    op.create_index(op.f("idx_permission_audit_log_team_time"), "permission_audit_log", ["team_id", "timestamp"], unique=False)
    op.create_index(op.f("idx_permission_audit_log_team_id"), "permission_audit_log", ["team_id"], unique=False)
    op.create_index(op.f("idx_permission_audit_log_resource_type"), "permission_audit_log", ["resource_type"], unique=False)
    op.create_index(op.f("idx_permission_audit_log_resource_granted_time"), "permission_audit_log", ["resource_type", "granted", "timestamp"], unique=False)
    op.create_index(op.f("idx_permission_audit_log_permission"), "permission_audit_log", ["permission"], unique=False)
    op.create_index(op.f("idx_permission_audit_log_granted"), "permission_audit_log", ["granted"], unique=False)
    op.drop_index(op.f("ix_performance_snapshots_worker_id"), table_name="performance_snapshots")
    op.drop_index(op.f("ix_performance_snapshots_timestamp"), table_name="performance_snapshots")
    op.drop_index(op.f("ix_performance_snapshots_host"), table_name="performance_snapshots")
    op.drop_index(op.f("ix_performance_metrics_window_start"), table_name="performance_metrics")
    op.drop_index(op.f("ix_performance_metrics_timestamp"), table_name="performance_metrics")
    op.drop_index(op.f("ix_performance_metrics_operation_type"), table_name="performance_metrics")
    op.drop_index(op.f("ix_performance_metrics_component"), table_name="performance_metrics")
    op.create_index(op.f("idx_performance_metrics_window_start"), "performance_metrics", ["window_start"], unique=False)
    op.create_index(op.f("idx_performance_metrics_timestamp"), "performance_metrics", ["timestamp"], unique=False)
    op.create_index(op.f("idx_performance_metrics_operation_type"), "performance_metrics", ["operation_type"], unique=False)
    op.create_index(op.f("idx_performance_metrics_component"), "performance_metrics", ["component"], unique=False)
    op.drop_index(op.f("ix_performance_aggregates_period_type"), table_name="performance_aggregates")
    op.drop_index(op.f("ix_performance_aggregates_period_start"), table_name="performance_aggregates")
    op.drop_index(op.f("ix_performance_aggregates_host"), table_name="performance_aggregates")
    op.drop_constraint(op.f("fk_pending_user_approvals_approved_by"), "pending_user_approvals", type_="foreignkey")
    op.create_index(op.f("idx_pending_user_approvals_email"), "pending_user_approvals", ["email"], unique=False)
    op.create_index(op.f("idx_pending_user_approvals_approved_by"), "pending_user_approvals", ["approved_by"], unique=False)
    op.create_unique_constraint(op.f("uq_password_reset_tokens_token_hash"), "password_reset_tokens", ["token_hash"])
    op.drop_index(op.f("ix_observability_traces_user_email"), table_name="observability_traces")
    op.drop_index(op.f("ix_observability_traces_start_time"), table_name="observability_traces")
    op.create_index(op.f("idx_observability_traces_user_status_time"), "observability_traces", ["user_email", "status", "start_time"], unique=False)
    op.create_index(op.f("idx_observability_traces_status_start_time"), "observability_traces", ["status", "start_time"], unique=False)
    op.create_index(op.f("idx_observability_traces_status_method_time"), "observability_traces", ["status", "http_method", "start_time"], unique=False)
    op.create_index(op.f("idx_observability_traces_name"), "observability_traces", ["name"], unique=False)
    op.create_index(op.f("idx_observability_traces_http_method_start_time"), "observability_traces", ["http_method", "start_time"], unique=False)
    op.create_index(op.f("idx_observability_traces_duration_ms"), "observability_traces", ["duration_ms"], unique=False)
    op.drop_index(op.f("ix_observability_spans_trace_id"), table_name="observability_spans")
    op.drop_index(op.f("ix_observability_spans_start_time"), table_name="observability_spans")
    op.drop_index(op.f("ix_observability_spans_resource_type"), table_name="observability_spans")
    op.drop_index(op.f("ix_observability_spans_resource_name"), table_name="observability_spans")
    op.drop_index(op.f("ix_observability_spans_resource_id"), table_name="observability_spans")
    op.drop_index(op.f("ix_observability_spans_parent_span_id"), table_name="observability_spans")
    op.create_index(op.f("idx_observability_spans_trace_resource_time"), "observability_spans", ["trace_id", "resource_type", "start_time"], unique=False)
    op.create_index(op.f("idx_observability_spans_trace_id_start_time"), "observability_spans", ["trace_id", "start_time"], unique=False)
    op.create_index(op.f("idx_observability_spans_resource_type_start_time"), "observability_spans", ["resource_type", "start_time"], unique=False)
    op.create_index(op.f("idx_observability_spans_resource_status_time"), "observability_spans", ["resource_type", "status", "start_time"], unique=False)
    op.create_index(op.f("idx_observability_spans_name"), "observability_spans", ["name"], unique=False)
    op.create_index(op.f("idx_observability_spans_kind_status"), "observability_spans", ["kind", "status"], unique=False)
    op.create_index(op.f("idx_observability_spans_duration_ms"), "observability_spans", ["duration_ms"], unique=False)
    op.drop_index(op.f("ix_observability_saved_queries_user_email"), table_name="observability_saved_queries")
    op.drop_index(op.f("ix_observability_saved_queries_name"), table_name="observability_saved_queries")
    op.create_index(op.f("idx_observability_saved_queries_name"), "observability_saved_queries", ["name"], unique=False)
    op.drop_index(op.f("ix_observability_metrics_trace_id"), table_name="observability_metrics")
    op.drop_index(op.f("ix_observability_metrics_timestamp"), table_name="observability_metrics")
    op.drop_index(op.f("ix_observability_metrics_resource_type"), table_name="observability_metrics")
    op.drop_index(op.f("ix_observability_metrics_resource_id"), table_name="observability_metrics")
    op.drop_index(op.f("ix_observability_metrics_name"), table_name="observability_metrics")
    op.drop_index(op.f("ix_observability_events_timestamp"), table_name="observability_events")
    op.drop_index(op.f("ix_observability_events_span_id"), table_name="observability_events")
    op.drop_index(op.f("ix_observability_events_severity"), table_name="observability_events")
    op.create_index(op.f("idx_observability_events_span_id_timestamp"), "observability_events", ["span_id", "timestamp"], unique=False)
    op.drop_constraint(op.f("uq_grpc_services_slug"), "grpc_services", type_="unique")
    op.drop_constraint(op.f("uq_grpc_services_name"), "grpc_services", type_="unique")
    op.create_index(op.f("idx_grpc_services_team_id"), "grpc_services", ["team_id"], unique=False)
    op.create_index(op.f("idx_grpc_services_slug"), "grpc_services", ["slug"], unique=1)
    op.create_index(op.f("idx_grpc_services_name"), "grpc_services", ["name"], unique=1)
    op.alter_column("grpc_services", "tags", existing_type=sqlite.JSON(), nullable=True)
    op.alter_column("grpc_services", "discovered_services", existing_type=sqlite.JSON(), nullable=True)
    op.alter_column("grpc_services", "grpc_metadata", existing_type=sqlite.JSON(), nullable=True)
    op.drop_index(op.f("ix_email_users_email"), table_name="email_users")
    op.create_index(op.f("idx_email_users_email"), "email_users", ["email"], unique=False)
    op.drop_constraint(op.f("fk_email_teams_created_by"), "email_teams", type_="foreignkey")
    op.create_index(op.f("idx_email_teams_visibility_active_created"), "email_teams", ["visibility", "is_active", "created_at"], unique=False)
    op.create_index(op.f("idx_email_teams_creator_personal_active"), "email_teams", ["created_by", "is_personal", "is_active"], unique=False)
    op.create_index(op.f("idx_email_teams_created_by"), "email_teams", ["created_by"], unique=False)
    op.drop_constraint(op.f("fk_email_team_members_user_email"), "email_team_members", type_="foreignkey")
    op.drop_constraint(op.f("fk_email_team_members_invited_by"), "email_team_members", type_="foreignkey")
    op.drop_constraint(op.f("fk_email_team_members_team_id"), "email_team_members", type_="foreignkey")
    op.create_index(op.f("idx_email_team_members_user_team_active"), "email_team_members", ["user_email", "team_id", "is_active"], unique=False)
    op.create_index(op.f("idx_email_team_members_user_email"), "email_team_members", ["user_email"], unique=False)
    op.create_index(op.f("idx_email_team_members_team_role_active"), "email_team_members", ["team_id", "role", "is_active"], unique=False)
    op.create_index(op.f("idx_email_team_members_team_id"), "email_team_members", ["team_id"], unique=False)
    op.create_index(op.f("idx_email_team_members_team_active_count"), "email_team_members", ["team_id", "is_active"], unique=False)
    op.create_index(op.f("idx_email_team_members_invited_by"), "email_team_members", ["invited_by"], unique=False)
    op.drop_constraint(op.f("fk_email_team_member_history_team_member_id"), "email_team_member_history", type_="foreignkey")
    op.create_foreign_key(op.f("fk_email_team_member_history_team_member_id"), "email_team_member_history", "email_team_members", ["team_member_id"], ["id"])
    op.create_index(op.f("idx_email_team_member_history_user_email"), "email_team_member_history", ["user_email"], unique=False)
    op.create_index(op.f("idx_email_team_member_history_team_member_id"), "email_team_member_history", ["team_member_id"], unique=False)
    op.create_index(op.f("idx_email_team_member_history_team_id"), "email_team_member_history", ["team_id"], unique=False)
    op.create_index(op.f("idx_email_team_member_history_action_by"), "email_team_member_history", ["action_by"], unique=False)
    op.drop_constraint(op.f("fk_email_team_join_requests_team_id"), "email_team_join_requests", type_="foreignkey")
    op.drop_constraint(op.f("fk_email_team_join_requests_user_email"), "email_team_join_requests", type_="foreignkey")
    op.drop_constraint(op.f("fk_email_team_join_requests_reviewed_by"), "email_team_join_requests", type_="foreignkey")
    op.create_index(op.f("idx_email_team_join_requests_user_status_time"), "email_team_join_requests", ["user_email", "status", "requested_at"], unique=False)
    op.create_index(op.f("idx_email_team_join_requests_user_email"), "email_team_join_requests", ["user_email"], unique=False)
    op.create_index(op.f("idx_email_team_join_requests_team_status_time"), "email_team_join_requests", ["team_id", "status", "requested_at"], unique=False)
    op.create_index(op.f("idx_email_team_join_requests_team_id"), "email_team_join_requests", ["team_id"], unique=False)
    op.create_index(op.f("idx_email_team_join_requests_reviewed_by"), "email_team_join_requests", ["reviewed_by"], unique=False)
    op.drop_constraint(op.f("fk_email_team_invitations_team_id"), "email_team_invitations", type_="foreignkey")
    op.drop_constraint(op.f("fk_email_team_invitations_invited_by"), "email_team_invitations", type_="foreignkey")
    op.create_index(op.f("idx_email_team_invitations_team_id"), "email_team_invitations", ["team_id"], unique=False)
    op.create_index(op.f("idx_email_team_invitations_team_active_created"), "email_team_invitations", ["team_id", "is_active", "invited_at"], unique=False)
    op.create_index(op.f("idx_email_team_invitations_invited_by"), "email_team_invitations", ["invited_by"], unique=False)
    op.create_index(op.f("idx_email_team_invitations_email_active_created"), "email_team_invitations", ["email", "is_active", "invited_at"], unique=False)
    op.drop_index(op.f("ix_email_auth_events_user_email"), table_name="email_auth_events")
    op.create_index(op.f("idx_email_auth_events_user_type_time"), "email_auth_events", ["user_email", "event_type", "timestamp"], unique=False)
    op.create_index(op.f("idx_email_auth_events_user_email"), "email_auth_events", ["user_email"], unique=False)
    op.create_index(op.f("idx_email_auth_events_type_success_time"), "email_auth_events", ["event_type", "success", "timestamp"], unique=False)
    op.create_index(op.f("idx_email_auth_events_timestamp"), "email_auth_events", ["timestamp"], unique=False)
    op.create_index(op.f("idx_email_auth_events_success_time"), "email_auth_events", ["success", "timestamp"], unique=False)
    op.create_index(op.f("idx_email_auth_events_success"), "email_auth_events", ["success"], unique=False)
    op.create_index(op.f("idx_email_auth_events_ip_time"), "email_auth_events", ["ip_address", "timestamp"], unique=False)
    op.create_index(op.f("idx_email_auth_events_ip_address"), "email_auth_events", ["ip_address"], unique=False)
    op.create_index(op.f("idx_email_auth_events_event_type"), "email_auth_events", ["event_type"], unique=False)
    op.drop_constraint(op.f("fk_email_api_tokens_user_email"), "email_api_tokens", type_="foreignkey")
    op.drop_constraint(op.f("fk_email_api_tokens_server_id"), "email_api_tokens", type_="foreignkey")
    op.drop_constraint(op.f("fk_email_api_tokens_team_id"), "email_api_tokens", type_="foreignkey")
    op.drop_index(op.f("ix_email_api_tokens_user_email"), table_name="email_api_tokens")
    op.drop_index(op.f("ix_email_api_tokens_team_id"), table_name="email_api_tokens")
    op.drop_index("idx_email_api_tokens_jti", table_name="email_api_tokens")
    op.create_index(op.f("idx_email_api_tokens_user_active_created"), "email_api_tokens", ["user_email", "is_active", "created_at"], unique=False)
    op.create_index(op.f("idx_email_api_tokens_team_id"), "email_api_tokens", ["team_id"], unique=False)
    op.create_index(op.f("idx_email_api_tokens_team_active_created"), "email_api_tokens", ["team_id", "is_active", "created_at"], unique=False)
    op.create_index(op.f("idx_email_api_tokens_server_id"), "email_api_tokens", ["server_id"], unique=False)
    op.create_index(op.f("idx_email_api_tokens_last_used"), "email_api_tokens", ["last_used"], unique=False)
    op.drop_index(op.f("ix_audit_trails_user_id"), table_name="audit_trails")
    op.drop_index(op.f("ix_audit_trails_user_email"), table_name="audit_trails")
    op.drop_index(op.f("ix_audit_trails_timestamp"), table_name="audit_trails")
    op.drop_index(op.f("ix_audit_trails_team_id"), table_name="audit_trails")
    op.drop_index(op.f("ix_audit_trails_success"), table_name="audit_trails")
    op.drop_index(op.f("ix_audit_trails_resource_type"), table_name="audit_trails")
    op.drop_index(op.f("ix_audit_trails_resource_id"), table_name="audit_trails")
    op.drop_index(op.f("ix_audit_trails_requires_review"), table_name="audit_trails")
    op.drop_index(op.f("ix_audit_trails_request_id"), table_name="audit_trails")
    op.drop_index(op.f("ix_audit_trails_data_classification"), table_name="audit_trails")
    op.drop_index(op.f("ix_audit_trails_correlation_id"), table_name="audit_trails")
    op.drop_index(op.f("ix_audit_trails_action"), table_name="audit_trails")
    op.create_index(op.f("idx_audit_trails_user_id"), "audit_trails", ["user_id"], unique=False)
    op.create_index(op.f("idx_audit_trails_user_email"), "audit_trails", ["user_email"], unique=False)
    op.create_index(op.f("idx_audit_trails_timestamp"), "audit_trails", ["timestamp"], unique=False)
    op.create_index(op.f("idx_audit_trails_team_id"), "audit_trails", ["team_id"], unique=False)
    op.create_index(op.f("idx_audit_trails_success"), "audit_trails", ["success"], unique=False)
    op.create_index(op.f("idx_audit_trails_resource_type"), "audit_trails", ["resource_type"], unique=False)
    op.create_index(op.f("idx_audit_trails_resource_id"), "audit_trails", ["resource_id"], unique=False)
    op.create_index(op.f("idx_audit_trails_requires_review"), "audit_trails", ["requires_review"], unique=False)
    op.create_index(op.f("idx_audit_trails_request_id"), "audit_trails", ["request_id"], unique=False)
    op.create_index(op.f("idx_audit_trails_data_classification"), "audit_trails", ["data_classification"], unique=False)
    op.create_index(op.f("idx_audit_trails_correlation_id"), "audit_trails", ["correlation_id"], unique=False)
    op.create_index(op.f("idx_audit_trails_action"), "audit_trails", ["action"], unique=False)
    op.alter_column("audit_trails", "resource_id", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.drop_index(op.f("ix_a2a_task_events_a2a_agent_id"), table_name="a2a_task_events")
    op.create_index(op.f("ix_a2a_task_events_agent_id"), "a2a_task_events", ["a2a_agent_id"], unique=False)
    op.drop_constraint(op.f("fk_a2a_agents_tool_id"), "a2a_agents", type_="foreignkey")
    op.drop_constraint(op.f("fk_a2a_agents_team_id"), "a2a_agents", type_="foreignkey")
    op.drop_constraint("uq_team_owner_slug_a2a_agent", "a2a_agents", type_="unique")
    op.drop_index("idx_a2a_agents_tool_id", table_name="a2a_agents")
    op.create_unique_constraint(op.f("uq_team_owner_slug_a2a_agents"), "a2a_agents", ["team_id", "owner_email", "slug"])
    op.create_index(op.f("ix_a2a_agents_uaid"), "a2a_agents", ["uaid"], unique=1)
    op.create_index(op.f("idx_a2a_agents_visibility_active_created"), "a2a_agents", ["visibility", "enabled", "created_at"], unique=False)
    op.create_index(op.f("idx_a2a_agents_visibility"), "a2a_agents", ["visibility"], unique=False)
    op.create_index(op.f("idx_a2a_agents_team_visibility_active_created"), "a2a_agents", ["team_id", "visibility", "enabled", "created_at"], unique=False)
    op.create_index(op.f("idx_a2a_agents_team_visibility"), "a2a_agents", ["team_id", "visibility"], unique=False)
    op.create_index(op.f("idx_a2a_agents_team_id"), "a2a_agents", ["team_id"], unique=False)
    op.create_index(op.f("idx_a2a_agents_slug_visibility"), "a2a_agents", ["slug", "visibility"], unique=False)
    op.create_index(op.f("idx_a2a_agents_slug"), "a2a_agents", ["slug"], unique=False)
    op.create_index(op.f("idx_a2a_agents_owner_visibility"), "a2a_agents", ["owner_email", "visibility"], unique=False)
    op.create_index(op.f("idx_a2a_agents_name"), "a2a_agents", ["name"], unique=False)
    op.create_index(op.f("idx_a2a_agents_enabled"), "a2a_agents", ["enabled"], unique=False)
    op.alter_column("a2a_agents", "tags", existing_type=sqlite.JSON(), nullable=True)
    op.alter_column("a2a_agents", "reachable", existing_type=sa.BOOLEAN(), nullable=True, existing_server_default=sa.text("'1'"))
    op.alter_column("a2a_agents", "enabled", existing_type=sa.BOOLEAN(), nullable=True, existing_server_default=sa.text("'1'"))
    op.alter_column("a2a_agents", "auth_type", existing_type=sa.String(length=20), type_=sa.VARCHAR(length=50), existing_nullable=True)
    op.alter_column("a2a_agents", "config", existing_type=sqlite.JSON(), nullable=True)
    op.alter_column("a2a_agents", "capabilities", existing_type=sqlite.JSON(), nullable=True)
    op.drop_column("a2a_agents", "tool_id")
    op.alter_column("a2a_agent_metrics_hourly", "created_at", existing_type=sa.DATETIME(), nullable=True, existing_server_default=sa.text("(CURRENT_TIMESTAMP)"))
    op.drop_index(op.f("ix_a2a_agent_metrics_timestamp"), table_name="a2a_agent_metrics")
    op.drop_index(op.f("ix_a2a_agent_metrics_a2a_agent_id"), table_name="a2a_agent_metrics")
    op.create_index(op.f("idx_a2a_agent_metrics_agent_is_success"), "a2a_agent_metrics", ["a2a_agent_id", "is_success"], unique=False)
    op.create_index(op.f("idx_a2a_agent_metrics_a2a_agent_id"), "a2a_agent_metrics", ["a2a_agent_id"], unique=False)
    op.drop_table("server_a2a_association")
    op.drop_index(op.f("ix_tool_metrics_tool_id"), table_name="tool_metrics")
    op.drop_index(op.f("ix_tool_metrics_timestamp"), table_name="tool_metrics")
    op.drop_table("tool_metrics")
    op.drop_table("server_tool_association")
    op.drop_table("server_resource_association")
    op.drop_table("server_prompt_association")
    op.drop_table("resource_subscriptions")
    op.drop_index(op.f("ix_resource_metrics_timestamp"), table_name="resource_metrics")
    op.drop_index(op.f("ix_resource_metrics_resource_id"), table_name="resource_metrics")
    op.drop_table("resource_metrics")
    op.drop_index(op.f("ix_prompt_metrics_timestamp"), table_name="prompt_metrics")
    op.drop_index(op.f("ix_prompt_metrics_prompt_id"), table_name="prompt_metrics")
    op.drop_table("prompt_metrics")
    op.drop_index("idx_tools_created_at_id", table_name="tools")
    op.drop_table("tools")
    op.drop_index(op.f("ix_server_metrics_timestamp"), table_name="server_metrics")
    op.drop_index(op.f("ix_server_metrics_server_id"), table_name="server_metrics")
    op.drop_table("server_metrics")
    op.drop_index("uq_team_owner_uri_resource_local", table_name="resources", postgresql_where=sa.text("gateway_id IS NULL"), sqlite_where=sa.text("gateway_id IS NULL"))
    op.drop_index("idx_resources_created_at_id", table_name="resources")
    op.drop_table("resources")
    op.drop_index("uq_team_owner_name_prompt_local", table_name="prompts", postgresql_where=sa.text("gateway_id IS NULL"), sqlite_where=sa.text("gateway_id IS NULL"))
    op.drop_index("idx_prompts_created_at_id", table_name="prompts")
    op.drop_table("prompts")
    op.drop_table("oauth_tokens")
    op.drop_index("idx_oauth_state_lookup", table_name="oauth_states")
    op.drop_table("oauth_states")
    op.drop_index("idx_servers_created_at_id", table_name="servers")
    op.drop_table("servers")
    op.drop_index("idx_gateways_created_at_id", table_name="gateways")
    op.drop_table("gateways")
    op.drop_index("ix_a2a_agent_plugin_bindings_team_id", table_name="a2a_agent_plugin_bindings")
    op.drop_index("ix_a2a_agent_plugin_bindings_binding_reference_id", table_name="a2a_agent_plugin_bindings")
    op.drop_index("ix_a2a_agent_plugin_bindings_agent_name", table_name="a2a_agent_plugin_bindings")
    op.drop_table("a2a_agent_plugin_bindings")
    op.drop_table("mcp_messages")
    op.drop_table("mcp_sessions")
    op.drop_table("global_config")
    # ### end Alembic commands ###
